### ISSUE TITLE
Typo in a file

### ISSUE THREAD

**Issue by mica16** [jwt-scala/jwt-scala#1]
In the legacy version of JwtBase64Impl.scala, you have this:

```
def decode(value: Array[Byte]): Array[Byte] = codec.encode(value)
```

=> should be replaced by: 

```
def decode(value: Array[Byte]): Array[Byte] = codec.decode(value)
```

Furthermore, standard use of JWT mentions an AuthorizationHeader with a Bearer String: 
"Authorization Bearer myToken".

So this lines would lead to an error when decoding step takes place: 

```
Play.maybeApplication.flatMap(_.configuration.getString("session.jwtName")).getOrElse("Authorization")
```

What I made actually is to alter this line as follows in order to ONLY get the token: 

```
request.headers.get(JwtSession.HEADER_NAME).flatMap(_.split(" ").drop(1).headOption).map(JwtSession.deserialize).getOrElse(JwtSession())
```

in order to retrieve the key without the `Bearer` string, that would break the "decode" step.

Otherwise I use the whole with Play 2.3.7 and it works great ! Thanks for the job :) 

May you create an SBT entry in order to integrate it easily in any app?

Michael

**Comment by pauldijou** [comment]
Good catch for the typo. I didn't test this code yet because I couldn't manage to have the project compiled again several Java versions with different source code, so only Java 8 for now... It's super easy to drop to Java 6 or Java 7 though, it's just switching to the correct source directory in the Build.scala.

I added support for a token prefix for the "Bearer" stuff. See https://github.com/pauldijou/jwt-scala/commit/609eea717255a4dbff3f4feb79c8c51a96c1ddd4

Glad to hear it works fine, I never used it in production so far to be honest. I will no publish it nor create an SBT entry right now, sorry. I would like to finish it more, add tests for the Play part and give more thoughts about the API before that. Unfortunately, I'm currently travelling until May 2015... so it will have to wait a bit.

Since you are probably one of the few people really using this project right now, feel free to give any feedback on the API, I will catch up and use it before the first real release.

Cheers
