### ISSUE TITLE
Support for Scala 2.13.0-M5

### ISSUE THREAD

**Issue by ennru** [jwt-scala/jwt-scala#115]
Play JSON 2.7.1 is available for 2.13.0-M5.

I'm not on top of the other dependencies, yet.

**Comment by ennru** [comment]
```
io.argonaut#argonaut_2.13.0-M5;6.2.2: not found
com.lihaoyi#upickle_2.13.0-M5;0.7.1: not found
org.scalatestplus.play#scalatestplus-play_2.13.0-M5;4.0.0: not found
```

**Comment by pauldijou** [comment]
@ennru Any idea how to configure cross Scala compilation per project?

**Comment by 2m** [comment]
In the latest sbt the `+compile` will actually switch and run the `compile` task according to the `crossScalaVersions` values on the per sub-project basis.

**Comment by pauldijou** [comment]
I tried `crossScalaVersions := Seq("2.13.0-M5")` and then `+coreProject/compile` just to see how it would go and I got `unresolved dependency: org.scalatest#scalatest_2.13.0-M5;3.0.5: not found`.

I don't really get it since `scalatest` is tagged with `% "test"`, so why is it even showing during the compilation step? Shouldn't it be during tests only? (which, to be fair, will be a trouble anyway since I would like to run those tests before publishing but at least it would make sense...)

Anyone has any idea? (mostly for compiling, I wouldn't mind releasing without testing since it's not a final Scala release yet)

**Comment by ennru** [comment]
You may use Scalatest `3.0.6-SNAP6` which is published for Scala 2.13.0-M5.

**Comment by 2m** [comment]
The "unresolved dependency" is actually this sbt issue: https://github.com/sbt/sbt/issues/3465

You need to set `crossScalaVersions := List()` on the aggregate project for a workaround.

Here is a commit that adds 2.13 cross compilation and excludes a couple of projects. The `+update` runs successfully on that branch.

https://github.com/2m/jwt-scala/commit/bc5a9562786f3d4afcdf80a639751fa8ac99c13f

**Comment by pauldijou** [comment]
Should be available in 2.1.0

**Comment by ennru** [comment]
Thank you, quicker turn-around than I would have expected for this!

**Comment by pauldijou** [comment]
That's because @2m did everything, which was nice 😄
