### ISSUE TITLE
Stop using system clock

### ISSUE THREAD

**Issue by ratoshniuk** [jwt-scala/jwt-scala#118]
Hi, I am currently working on with your lib and issued with throwing JwsExpireException while JwtCirce.decode

In my opinion, it doesn't look like a pure function, I think we could make checking expiration not inside decoding a JWT.

Also, cats, scalaz have own abstraction above Clock and it would be nice to have own for mocking time during checking JwtTime exceptions

What do you think? 🤔🤔

**Comment by pauldijou** [comment]
Does it really throw or does it return a `Failure[JwtExpireException]`? `decode` functions should return a `Try`. The check is inside because I don't want users to forget about it and accept expired token.

You can use `JwtOptions` to disable expiration check and still parse an expired token.

I won't work on having an abstraction above Clock but if someone open a PR, I will review it for sure since it would make testing way easier.

**Comment by critium** [comment]
Being able to set the clock, would be greatly appreciated as it makes unit testing easier!

**Comment by francisdb** [comment]
this has been introduced in `3.1.0` but should have been `4.0.0` as this is a breaking change

we are seeing this because alpakka depends on 3.0.1 and we use 3.1.0:

```
java.lang.NoSuchMethodError: pdi.jwt.JwtTime$.nowSeconds()J
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleTokenApi.now(GoogleTokenApi.scala:26)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleTokenApi.getAccessToken(GoogleTokenApi.scala:41)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleSession.getNewToken(GoogleSession.scala:18)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleSession.$anonfun$getToken$1(GoogleSession.scala:29)
```
