### ISSUE TITLE
Does release 3.0.0 support java 1.8 ?

### ISSUE THREAD

**Issue by sim732** [jwt-scala/jwt-scala#128]
hi,

After upgrading from 2.1.0 to 3.0.0 got:

Uncaught error from thread [Dialup-akka.actor.default-dispatcher-4]: pdi/jwt/JwtArrayUtils has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Dialup]
java.lang.UnsupportedClassVersionError: pdi/jwt/JwtArrayUtils has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by pauldijou** [comment]
Short answer: yes, it does support Java 8, not sure what's going on here.

@brakthehack Could you take a look at this error? Is it worth using a Java file compared to just migrate it to a Scala one?

**Comment by brakthehack** [comment]
It looks like the java source was compiled using java11 before the library was published. I’m guessing that is the default on the CI server? It appears a Java 8 runtime isn’t too happy about that. My bet is that we need to set some javac options so that we compile our java sources for the minimum supported JRE version.

See: https://stackoverflow.com/questions/19208942/enforcing-java-version-for-scala-project-in-sbt

**Comment by pauldijou** [comment]
Should be fixed in 3.0.1 thanks to @brakthehack .
