### ISSUE TITLE
Allow secrets to be selected as part of the decoding process

### ISSUE THREAD

**Issue by jroper** [jwt-scala/jwt-scala#150]
As far as I can see, jwt-scala is not useful if you have more than one secret/key. Possibilities for this include:

* Secret rotation - it's a good practice to regularly rotate secrets, to do this, you need to concurrently accept tokens signed with both old and new secrets for the period of time where you start using the new secret, but there are tokens signed by the old secret that haven't yet expired.
* Per issuer secrets. You may have multiple services issuing JWTs, each with their own public/private key pair.

Ideally, information about which secret is being used should be in the JWT itself, for example, the `iss` claim may contain an identifier for the issuer, and the public key used to verify the signature for that issuers JWTs would be selected by inspecting that. To support this, the signature for decoding would have to be something in the form of `JwtClaim => Secret`.

Of course, this could be achieved by first decoding the claim without passing a secret and setting the signature option to false, reading the issuer, selecting a secret, and then decoding again with the secret, but then you're unnecessarily decoding the jwt twice.

**Comment by pauldijou** [comment]
I have concerns about going down that road... There is no specific reason to store that information in the claim, actually, I would probably use the [`kid` in the header](https://tools.ietf.org/html/rfc7515#section-4.1.4), so the signature would become `(JwtHeader, JwtClaim) => Secret`.

On top of that, what if for the per issuer secret you need to access some database or storage in an async way? To support that, the signature would not only be `(JwtHeader, JwtClaim) => Future<Secret>` but would also make all decoding functions async too.

I would rather keep the lib simple and let users deal with their specifics. True enough it's unfortunate to decode some parts twice, but if using the header, it should be a pretty small JSON. Since the content is just base 64 JSON, you can manually decode it without using jwt-scala with `signature` to `false`, this way you can only decode what you truly need.

An alternative for the secret rotation would be to decode with the new secret, and if it fails, try the old one, betting on the fact that over time, most users will use the new one.
