### ISSUE TITLE
JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by wbget** [jwt-scala/jwt-scala#36]
Exception in thread "main" java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
        at javax.crypto.JceSecurity.getInstance(JceSecurity.java:101)
        at javax.crypto.Mac.getInstance(Mac.java:222)
        at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:121)
        at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:150)
        at pdi.jwt.JwtUtils$.sign(JwtUtils.scala:159)
        at pdi.jwt.JwtCore$class.encode(Jwt.scala:80)
        at pdi.jwt.Jwt$.encode(Jwt.scala:23)
        at pdi.jwt.JwtCore$class.encode(Jwt.scala:109)
        at pdi.jwt.Jwt$.encode(Jwt.scala:23)
        at pdi.jwt.JwtCore$class.encode(Jwt.scala:149)
        at pdi.jwt.Jwt$.encode(Jwt.scala:23)

i use SBT assembly
i learn scala recently, i don't know how to fix the bug, maybe you can give me some advise.
Thanks.

**Comment by epiphyllum** [comment]
I also encounter the same problem  when assembled by  `sbt-assembly`

**Comment by pauldijou** [comment]
Sorry to hear that @epiphyllumh. I've never used `sbt-assembly` and don't really have time to give it a try but if you can debug where the problem come from, I will fix it ASAP.

**Comment by liyuntao** [comment]
The reason is: JCE requires JAR with Bouncy Castle to be signed and creating executable jar(fat-jar) ruins it.

For those who are using jwt-scala and want to use sbt-assembly for deployment, here's an solution.

First you must exclude bcpkix in `build.sbt`. Or make the package under `org.bouncycastle` to a provided dependency.

```scala
    libraryDependencies ++= Seq(
      "com.typesafe.akka" %% "akka-http"            % akkaHttpVersion,
      "com.typesafe.akka" %% "akka-http-spray-json" % akkaHttpVersion,
      "com.typesafe.akka" %% "akka-stream"          % akkaVersion,
      ("com.pauldijou"    %% "jwt-core"             % "0.14.0").exclude("org.bouncycastle", "bcpkix-jdk15on"),
      "org.bouncycastle"  %  "bcpkix-jdk15on"       % "1.57"          % Provided,
      "com.typesafe.akka" %% "akka-http-testkit"    % akkaHttpVersion % Test,
      "org.scalatest"     %% "scalatest"            % "3.0.1"         % Test
    )
```
Then download the two bouncycastle dependencies's jar file. Move them to `jre/lib/ext` and modify `jre/lib/security/java.security` accouding to [answer from jiangzx](https://stackoverflow.com/questions/13721579/jce-cannot-authenticate-the-provider-bc-in-java-swing-application)

  Here's an example Dockerfile for CI building(basically the same steps).
```Dockerfile
FROM example.com/base/java

RUN mkdir /app
WORKDIR /app

COPY lib/bcpkix-jdk15on-1.57.jar /opt/jdk1.8.0_111/jre/lib/ext/
COPY lib/bcprov-jdk15on-1.57.jar /opt/jdk1.8.0_111/jre/lib/ext/
RUN echo "security.provider.10=org.bouncycastle.jce.provider.BouncyCastleProvider" >> /opt/jdk1.8.0_111/jre/lib/security/java.security

COPY target/scala-2.12/app-assembly-0.1-SNAPSHOT.jar .
COPY run.sh .
RUN chmod +x /app/run.sh
ENTRYPOINT ["/app/run.sh"]
```

**Comment by xmeng1** [comment]
The version [3.0.0](https://github.com/pauldijou/jwt-scala/releases/tag/v3.0.0) has resolved this issue. Need not do this ~ see this PR: https://github.com/pauldijou/jwt-scala/pull/126/commits/940c14371dd30edd2f79ba366724bc94dbee80d0#
