### ISSUE TITLE
WebSockets authentication

### ISSUE THREAD

**Issue by max-peroch** [jwt-scala/jwt-scala#42]
Hi,

I was just wondering how you would do to authenticate Websockets with Play 2.5 and jwt-play ?

Thanks,

**Comment by pauldijou** [comment]
I've never done it, but there is [some doc](https://www.playframework.com/documentation/2.5.x/JavaWebSockets#Rejecting-a-WebSocket) on it, except that instead of using `session()`, you should get the `Authorization` HTTP header and apply `JwtSession.deserialize` to it. You will have your JWT session and you can check if it's ok or not.

**Comment by max-peroch** [comment]
Thanks for your answer, I guess my question wasn't clear, I should have specified that I've got this part. I was mostly curious if you have done a "WebsocketBuilder" or something like that before? But I've got my answer :) 

Thanks for your work and your time !
