### ISSUE TITLE
ionic2-jwt-play example

### ISSUE THREAD

**Issue by djonmayer** [jwt-scala/jwt-scala#43]
Hello. Can you make a standalone Play application using jwt-play and Ionic2 please?

**Comment by pauldijou** [comment]
Probably not. Since both Play and Ionic apps will be standalone, you already have the Play example inside this respository. As for the Ionic one, just search it on Google, I found [this one](https://auth0.com/blog/ionic-2-authentication-how-to-secure-your-mobile-app-with-jwt/) which look quite good.

Combine them together and here you have it.
