### ISSUE TITLE
Support play 2.4

### ISSUE THREAD

**Issue by alari** [jwt-scala/jwt-scala#5]
Play-json API has changed in 2.4. It would be great to have jwt-scala support for it.

**Comment by pauldijou** [comment]
Actually, code is ready but I cannot fully test it because all my integration tests are now failing thanks an error in Guice configuration or whatever. I'm not even using any DI at all...

Anyway, I pushed the code but I cannot release it until I got the tests running. I opened an issue on Play Framework. Let's see if we got an answer.

**Comment by pauldijou** [comment]
Sorry for the delay, I was finally able to fix the tests. `0.3.0` is out with full support of Play 2.4.0. Enjoy.

**Comment by alari** [comment]
thanks :)
