### ISSUE TITLE
Play request.jwtSession can't deserialize when using a non-empty claim

### ISSUE THREAD

**Issue by kheraud** [jwt-scala/jwt-scala#51]
Hello,

Maybe I am missing something but I can't figure out how to use custom claim (expiration and issuedAt) with Play sub project.

I have no problem to deserialize simple Payload (secret: changeme, algorythm: HS256): 
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZW1iZXIiOnsidXNlcklkIjoxLCJ1c2VyVXVpZCI6IkhlcmF1ZCBLYXJpbSJ9fQ.OU1-WxnNIE4CosHXds3jty0kJeRtfYeeJyahFkyTGSY` gives me :
`JwtSession({"typ":"JWT","alg":"HS256"},{"member":{"userId":1,"userUuid":"Heraud Karim"}},OU1-WxnNIE4CosHXds3jty0kJeRtfYeeJyahFkyTGSY)` as expected

But if I add specific claim the deserialized bearer is empty :
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0OTI3OTQwMjksIm1lbWJlciI6eyJ1c2VySWQiOjEsInVzZXJVdWlkIjoiSGVyYXVkIEthcmltIn19.TzVQSaoFNw41TKvdamAWUfEV2KwHpmCRTrGw9LArP74`gives me :
`JwtSession({"typ":"JWT","alg":"HS256"},{},)` instead of `JwtSession({"typ":"JWT","alg":"HS256"},{"exp": 1492794029,"member":{"userId":1,"userUuid":"Heraud Karim"}},TzVQSaoFNw41TKvdamAWUfEV2KwHpmCRTrGw9LArP74)`

I tried with 'exp' and 'iat' it fails to deserialize it. Tried with 0.12.1 and 0.11.0.

I am probably missing a step. Thanks for a hint

Karim

**Comment by pauldijou** [comment]
You are not missing anything. This was a design choice but to be honest, I'm still not sure if it was the best one.

The idea is that you will always be able to extract a `JwtSession` from the request. If it is valid, it will have all the data inside it. If it is invalid, it will be an empty session (no claim mostly). Since your token is expired regarding the `exp` value, you get an empty session. In this particular use case, the lib does not care why it is invalid, as long as it's not good, it considers it an empty session.

Try again with an  `exp` far away in the future and it should work just fine.

**Comment by kheraud** [comment]
Thanks for the reply. This design choice suits me well.

My issue is in fact related to “how is 'exp' implemented" and not about claim implementation.

Thanks for the explaination
