### ISSUE TITLE
request.jwtSession should be an Option

### ISSUE THREAD

**Issue by ScalaWilliam** [jwt-scala/jwt-scala#60]
Hi, I'm a user. Been having trouble since upgrading at some point (I can't identify exactly when the breakage occurred).

`request.jwtSession` returns a `JwtSession` all the time - when there is no value supplied there's a `.getOrElse(JwtSession())`.

This `JwtSession` call is impure as it depends on time (due to default claim).

Also for some reason the `request.jwtSession.isEmpty` does not return true for that default value, either. So the only way I can check for emptiness (ie no token) is to do `request.jwtSession.signature == ""` instead of `request.jwtSession.isEmpty`.

- https://github.com/ScalaWilliam/ActionFPS/issues/396
- https://github.com/ScalaWilliam/ActionFPS/issues/394

Hope this is clear.

**Comment by pauldijou** [comment]
`JwtSession` is working just like the `Session` inside Play. `request.session` will always return a session, and it will be empty if the cookie expired. So it's not pure indeed but that was the goal. Anyway, since it depends on time, event with an Option, it wouldn't be pure either.

The main problem is more about the `isEmpty`, I will try to take a look ASAP.
