### ISSUE TITLE
jwt-json-common (0.15.0) dependency not published to Maven

### ISSUE THREAD

**Issue by michalstutzmann** [jwt-scala/jwt-scala#81]
For some reason it has not been included in the latest publication: https://repo1.maven.org/maven2/com/pauldijou/jwt-json-common_2.12

**Comment by michalstutzmann** [comment]
Workaround until fixed:

```scala
"com.pauldijou" %% "jwt-circe" % "0.15.0",
"com.pauldijou" %% "jwt-json-common" % "0.14.1" force,
```

**Comment by pauldijou** [comment]
Yeah, I spent way too much of my WE updating to sbt 1.1.0 because running 0.13 started to have problems. It went kind of fine(ish) except for the publish which totally failed.

It looks like publishing will fail if a snapshot for a project is already existing in the Sonatype staging area. Since all projects are using the `jwt-core` one, they will all try to publish its snapshot. So publishing is now a big pain, tried to do it by hand by failed, sorry about that.

If anyone has a solution, I would be super thankfull since I don't know much about sbt.

**Comment by aisven** [comment]
I am not sure, but in build.sbt the command alias `publishAll` seems to have an incomplete list, since it does not include `publishCore`. This may have led to the current situation where jwt-json-common 0.15.0 is not up on Maven Central.
```
addCommandAlias("publishAll", ";+publishPlayJson;+publishJson4Native;+publishJson4Jackson;+publishCirce;+publishUpickle;+publishPlay")
```

**Comment by pauldijou** [comment]
The command is complete, it has been used for nearly every version until now just fine. Projects will also publish their dependencies and both `jwt-core` and `jwt-json-common` are dependencies of other projects.

Migrating to sbt 1.1.0 prevented me from using this command, I have no solution on how to fix it now unfortunately. I will try to publish the missing dependency as soon as I can.

**Comment by pauldijou** [comment]
Should be fixed.
