### ISSUE TITLE
Question about testing

### ISSUE THREAD

**Issue by Ideologue** [jwt-scala/jwt-scala#88]
How could we test controllers that extends Secure Controller  there are no sample test for those controllers in the sample apps

**Comment by pauldijou** [comment]
[This test](https://github.com/pauldijou/jwt-scala/blob/master/play/src/test/scala/JwtSessionSpec.scala) is using a Fake application to test its controllers, you can find [some helpers here](https://github.com/pauldijou/jwt-scala/blob/master/play/src/test/scala/PlayFixture.scala). Not fully sure how it would apply to a real app... It's been ages since I've done any Scala, no idea how the testing ecosystem is anymore.

**Comment by Ideologue** [comment]
Thank you very much for your replay
